import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Text2Obj from "../components/Text2Obj";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text2Obj />
      <Overlay />
    </>
  );
}

function Overlay() {
  return (
    <>
      <div
        style={{
          color: "#808080",
          position: "absolute",
          top: 40,
          left: 40,
          fontSize: "13px",
        }}
      >
        GenesisNLO — by Andreas E. Eriksen
      </div>
    </>
  );
}
